# Generated by Django 4.0.3 on 2022-04-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_slug_author_adress_author_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slug',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='slug',
            new_name='tag',
        ),
    ]
