# Generated by Django 4.0.3 on 2022-05-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author_alter_post_image_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('content', models.TextField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='commentary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.commentary'),
        ),
    ]
