# Generated by Django 4.0.3 on 2022-05-06 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_commentary_post_commentary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='commentary',
        ),
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='blog.post'),
        ),
    ]
